import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Valentina Panic Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white">
        <section className="min-h-screen">
          <nav className="bg-red-300 py-10 mb-10 flex justify-between">
            <h1 className="text-xl ml-3">Valentina Panic</h1>
            <ul className="flex justify-around">
              <li>Resume</li>
              <li>About</li>
              <li>Projects</li>
            </ul>
          </nav>
        </section>
      </main>
    </>
  );
}
